    <nav class="container navbar navbar-expand-lg bg-light" style="border-radius: 10px;  font-family: 'Open Sans', sans-serif;">
	<a class="navbar-brand" href="https://www.vdiec.com"><img src="images/logo.png" alt="logo" style="width:90px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon">
            <i class="fa fa-navicon"></i>
            </span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <!-- md-auto: left, ml-auto: right, mx-auto: center -->
            <ul class="navbar-nav md-auto">
                <li class="nav-item" style="color:blue">
                    <a class="nav-link" href="index.php" id="0" onClick="nav_item_selected(0)" >My Dashboard</a>
                </li>
				<li class="nav-item">
                    <a class="nav-link" href="admin.php" id="1" onClick="nav_item_selected(1)">Admin Management</a>
                </li>
				
                <li class="nav-item">
                    <a class="nav-link" href="lead.php" id="2" onClick="nav_item_selected(2)">Lead Management</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="calling.php" id="3" onClick="nav_item_selected(3)">Calling Management</a>
                </li>

				
            </ul>
        </div>
		
    </nav>

